#! /bin/csh -f

#Usage: editWM subjectFolder

set bin = /home/camachocm2/Analysis/aggregate_anats/child_cortex/fs_scripts
setenv SUBJECTS_DIR /moochie/Cat/Aggregate_anats/subjects_dir
set sub = $argv[1]


if( -e $SUBJECTS_DIR/$sub ) then        		
	echo 
	echo "found subject"
	echo
	echo "Using "$SUBJECTS_DIR "/" $sub
	echo
		tkmedit $sub brainmask.mgz lh.white -aux wm.mgz -aux-surface rh.white -tcl $bin/tkmedit_WMedit.tcl

else
	echo " Could not find "$sub"."
    exit 1;
endif

echo ""
echo ""
echo "Who's awesome? You're awesome!"
echo ""
echo ""